### ISSUE TITLE
Qt5WebEngine not found

### ISSUE THREAD

**Issue by NeodarZ** [daleglass/vircadia-builder#10]
The compilation failed and complain about that QT5WeEngine is not found, see below the logs. 

Your script will also build QT5WeEngine or it use some system libraries ? If it's use some system libraries there's still a good chance that my system is broken, as always. Sorry if for you the response is obvious, I sometimes have trouble compiling. :/

My system is Archlinux and yes I noted the line : 
```
Sorry, Arch Linux is not supported. Please consider helping us out.
```

I only past here the part that seem interesting. I also attach all the log about QT installation and  the CMakeError logs.

```
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (QUAZIP)
  does not match the name of the calling package (QuaZip).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindQuaZip.cmake:27 (find_package_handle_standard_args)
  /home/neodarz/Vircadia/vcpkg/47e0fb40/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  libraries/script-engine/CMakeLists.txt:10 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found QUAZIP: /home/neodarz/Vircadia/build/ext/makefiles/quazip/project/include  
-- Found Bullet: /home/neodarz/Vircadia/vcpkg/47e0fb40/installed/x64-linux/include/bullet  
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (QUAZIP)
  does not match the name of the calling package (QuaZip).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindQuaZip.cmake:27 (find_package_handle_standard_args)
  /home/neodarz/Vircadia/vcpkg/47e0fb40/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  cmake/macros/TargetQuazip.cmake:10 (find_package)
  domain-server/CMakeLists.txt:30 (target_quazip)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Qt5WebEngine (missing: Qt5WebEngine_DIR)
CMake Warning at /home/neodarz/Vircadia/vcpkg/47e0fb40/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
  Found package configuration file:

    /home/neodarz/Vircadia/qt5-install/lib/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "WebEngine" config file at
  "/home/neodarz/Vircadia/qt5-install/lib/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake"


  

Call Stack (most recent call first):
  interface/CMakeLists.txt:92 (find_package)


CMake Error at /home/neodarz/Vircadia/vcpkg/47e0fb40/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
  Could not find a package configuration file provided by "Qt5WebEngine" with
  any of the following names:

    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

  Add the installation prefix of "Qt5WebEngine" to CMAKE_PREFIX_PATH or set
  "Qt5WebEngine_DIR" to a directory containing one of the above files.  If
  "Qt5WebEngine" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/neodarz/Vircadia/qt5-install/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /home/neodarz/Vircadia/vcpkg/47e0fb40/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  cmake/macros/SetupHifiLibrary.cmake:68 (find_package)
  libraries/audio-client/CMakeLists.txt:5 (setup_hifi_library)


-- Configuring incomplete, errors occurred!
```
[logs_install_qt.log](https://github.com/daleglass/vircadia-builder/files/4617633/logs_install_qt.log)
[CMakeError.log](https://github.com/daleglass/vircadia-builder/files/4617644/CMakeError.log)

**Comment by daleglass** [comment]
It'll build Qt, which includes QtWebEngine.

Building Qt is currently required, because there's an important patch that didn't make it yet into any Qt release. It should be in Qt 5.15, which should come out on 19th. But before that some fixes will be needed to the code to build against newer versions of Qt.

**Comment by NeodarZ** [comment]
Ok thanks for this information.

I investigated to find more information about why QtWebEngine has not been cloned.

First the folder `/home/neodarz/Vircadia/qt5-install/lib/cmake/Qt5WebEngine` doesn't exist and somewhere in the output there is a complain about the submobule qtwebengine-chromium who doesn't exist and it won't build QtWebEngine.

Here I the exact log:
```
Submodule qtwebengine-chromium does not exist. Run 'git submodule update --init'.
QtWebEngine will not be built.
```

And here is a complete output of the [log](https://github.com/daleglass/vircadia-builder/files/4629962/log.txt) (minus the fact I have make a ^c some times after see the string `QtWebEngine will not be built.`)

Between I forgotten to precise the commande used, there it is: `./vircadia-builder --distro custom --auto`.

So now I need to find why the submodule qtwebengine-chromium does not exist, maybe I missing something?

**Comment by NeodarZ** [comment]
Ok so finally the solution is very simple.

The script is not compatible with git 2.13 and later and a stupid fix is to use `--recurse-submodules` instead of `--recursive`.

I think a better fix can be to check the git version used in the `git_clone` function and use the correct option in regards to the git version.

After that the script will be compatible with Archlinux (If there is no other issue, It currently building QtWebEngine)

**Comment by daleglass** [comment]
Huh, that is odd. My local git is version 2.25.4.

I'll look into it, thanks for the help.

**Comment by NeodarZ** [comment]
Ok I'm sorry. I don't know why but now it's clone the submodule qtwebengine-chromium with the `--recursive` option...
In fact I've rechecked the help of my git-clone command and there is an alias for `--recursive` to `--recurse-submodules`, the man page said nothing about the alias.

I didn't update my git package or reinstalled it so I'm a bit surprised by what's in going on...

I will wait the end of the build (with the `--recursive` option) for see if there is an error.

**Comment by daleglass** [comment]
I heard from another user with the same issue and this should be fixed. Please reopen if not.
