### ISSUE TITLE
AppImage does always uses integrated libstdc++.so.6

### ISSUE THREAD

**Issue by JulianGro** [daleglass/vircadia-builder#19]
Having `libstdc++.so.6` breaks a lot of distributions according to the AppImage docs. In practice this broke the AppImage on Arch Linux. You can work around the problem by using something like
```
LD_PRELOAD=/usr/lib/libstdc++.so.6 ./Vircadia-Alpha-2020.2.3-Asteria.AppImage
```

https://docs.appimage.org/packaging-guide/advanced/troubleshooting.html?highlight=libstdc

**Comment by daleglass** [comment]
Oops. This looks like a bug in a regular expression.
