### ISSUE TITLE
Cannot set some values asked when installing

### ISSUE THREAD

**Issue by NeodarZ** [daleglass/vircadia-builder#9]
Hi, I have a little problem.

Before installing, your script will ask for some info, in function `collect_info()` to be more precise, and It tell me that I can press ENTER to set default value.

So I press ENTER for some questions but It don't set the value in the loop with the default option and set it to "". After that the installer complain about that an empty string cannot be a valid path.
I checked the source code but I don't know If the `readline()` function set a default value if you send an empty string... ([here for example](https://github.com/daleglass/vircadia-builder/blob/master/vircadia-builder#L1338))

I also have the same error message If I set, for example, the installation dir path and failed. I have no idea why for the moment.

I can bypass this with the `--auto` option but it's not very usefull.

I'm on archlinux and since archlinux is not supported by your script I use the `custom` distribution.

**Comment by daleglass** [comment]
Pre-filling the default is a feature of `Term::ReadLine::Gnu`. You must have the non-GNU variant.

For supported distros, the script makes sure to install that module.

**Comment by NeodarZ** [comment]
Oh yes sorry. After installing the package `community/perl-term-readline-gnu` it works as expected. 

For the custom distro it can be useful to explain somewhere what dependencies needed by the script to run no ? And maybe also for some other dependencies add some infos in FAQ ? I don't know if it's relevant...

In any case thanks!
